-- Rock Types

materials = {
    alabaster = { name="Alabaster", type="cluster_rock", parent="gypsum", 
        glyph=glyphs['power_of'], fg=colors['white'], bg=colors['grey'],
        hit_points = 110, mines_to="alabaster_powder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Alabaster_FloorRough.M_Alabaster_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Alabaster_FloorSmooth.M_Alabaster_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Alabaster_WallRough.M_Alabaster_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Alabaster_WallSmooth.M_Alabaster_WallSmooth'",
        description = "A soft rock that can be ground into plaster, or easily carved."
    },
    aluminium_rock = { name="Raw Aluminium", type="rock", layer="igneous", 
        glyph=glyphs['power_of'], fg=colors['white'], bg=colors['grey'],
        hit_points = 80, mines_to="ore", ore_materials = {"aluminium"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Bauxite_FloorRough.M_Bauxite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Bauxite_FloorSmooth.M_Bauxite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Bauxite_WallRough.M_Bauxite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Bauxite_WallSmooth.M_Bauxite_WallSmooth'",
        description = "An aluminium ore, that can be refined into useful metal."
    },
    alunite = { name="Alunite", type="rock", layer="igneous", 
        glyph=glyphs['backtick'], fg=colors['white'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Alunite_FloorRough.M_Alunite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Alunite_FloorSmooth.M_Alunite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Alunite_WallRough.M_Alunite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Alunite_WallSmooth.M_Alunite_WallSmooth'",
        description = "A hydrated aluminium potassium sulfate rock."
    },
    andesite = { name="Andesite", type="rock", layer="igneous", 
        glyph=glyphs['infinity'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Andesite_FloorRough.M_Andesite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Andesite_FloorSmooth.M_Andesite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Andesite_WallRough.M_Andesite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Andesite_WallSmooth.M_Andesite_WallSmooth'",
        description = "A common, extrusive igneous stone."
    },
    basalt = { name="Basalt", type="rock", layer="igneous", 
        glyph=glyphs['hash'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Basalt_FloorRough.M_Basalt_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Basalt_FloorSmooth.M_Basalt_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Basalt_WallRough.M_Basalt_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Basalt_WallSmooth.M_Basalt_WallSmooth'",
        description = "A common, extrusive igneous stone."
    },
    bauxite = { name="Bauxite", type="rock", layer="sedimentary", 
        glyph=glyphs['plus'], fg=colors['red'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"aluminium"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Bauxite_FloorRough.M_Bauxite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Bauxite_FloorSmooth.M_Bauxite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Bauxite_WallRough.M_Bauxite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Bauxite_WallSmooth.M_Bauxite_WallSmooth'",
        description = "An aluminium ore, that can be refined into useful metal."
    },
    bismunthine = { name="Bisminthine", type="rock", layer="sedimentary", 
        glyph=glyphs['percent'], fg=colors['white'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials={"bismuth"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Bismunthine_FloorRough.M_Bismunthine_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Bismunthine_FloorSmooth.M_Bismunthine_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Bismunthine_WallRough.M_Bismunthine_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Bismunthine_WallSmooth.M_Bismunthine_WallSmooth'",
        description = "A crystalline rock, similar to ammonia. Refines into Bismuth, used in bronzeworking."
    },
    bithumous_coal = { name="Bithumous Coal", type="rock", layer="sedimentary", 
        glyph=glyphs['sun'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="coal",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_BithuminousCoal_FloorRough.M_BithuminousCoal_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_BithuminousCoal_FloorSmooth.M_BithuminousCoal_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_BithuminousCoal_WallRough.M_BithuminousCoal_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_BithuminousCoal_WallSmoooth.M_BithuminousCoal_WallSmoooth'",
        description = "Sticky black rock from which one can extract coal and tar."
    },
    brimstone = { name="Brimstone", type="rock", layer="igneous", 
        glyph=glyphs['percent'], fg=colors['yellow'], bg=colors['grey'],
        hit_points = 100, mines_to="sulphur",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Brimstone_FloorRough.M_Brimstone_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Brimstone_FloorSmooth.M_Brimstone_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Brimstone_WallRough.M_Brimstone_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Brimstone_WallSmooth.M_Brimstone_WallSmooth'",
        description = "A smelly, sulphorous rock."
    },
    cassiterite = { name="Cassiterite", type="rock", layer="sedimentary", 
        glyph=glyphs['ukp'], fg=colors['yellow'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"tin"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Cassiterite_FloorRough.M_Cassiterite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Cassiterite_FloorSmooth.M_Cassiterite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Cassiterite_WallRough.M_Cassiterite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Cassiterite_WallSmooth.M_Cassiterite_WallSmooth'",
        description = "A dark crystalline rock."
    },
    chalk = { name="Chalk", type="rock", layer="sedimentary", 
        glyph=glyphs['one_quarter_solid'], fg=colors['white'], bg=colors['grey'],
        hit_points = 75, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Chalk_FloorRough.M_Chalk_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Chalk_FloorSmooth.M_Chalk_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Chalk_WallRough.M_Chalk_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Chalk_Wall_Smooth.M_Chalk_Wall_Smooth'",
        description = "A crumbly rock, commonly used for writing on walls."
    },
    chert = { name="Chert", type="rock", layer="sedimentary", 
        glyph=glyphs['equals'], fg=colors['purple'], bg=colors['grey'],
        hit_points = 75, mines_to="flint", mines_to_also="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Chert_FloorRough.M_Chert_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Chert_FloorSmooth.M_Chert_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Chert_WallRough.M_Chert_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Chert_WallSmooth.M_Chert_WallSmooth'",
        description = "A microcrystalline quartz rock."
    },
    chromite = { name="Chromite", type="rock", layer="igneous", 
        glyph=glyphs['equals'], fg=colors['white'], bg=colors['grey'],
        hit_points = 75, mines_to="ore", ore_materials = {"chromium"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Chromite_FloorRough.M_Chromite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Chromite_FloorSmooth.M_Chromite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Chromite_WallRough.M_Chromite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Chromite_WallSmooth.M_Chromite_WallSmooth'",
        description = "A metamorphic rock containing chrome ore."
    },
    cinnabar = { name="Cinnabar", type="rock", layer="igneous", 
        glyph=glyphs['ukp'], fg=colors['red'], bg=colors['grey'],
        hit_points = 115, mines_to="mercury_ore", -- TODO: Mercury should be treated differently,
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Cinnabar_FloorRough.M_Cinnabar_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Cinnabar_FloorSmooth.M_Cinnabar_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Cinnabar_WallRough.M_Cinnabar_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Cinnabar_Wall_Smooth.M_Cinnabar_Wall_Smooth'",
        description = "A red, crystalline rock."
    },
    claystone = { name="Claystone", type="rock", layer="sedimentary", 
        glyph=glyphs['comma'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 75, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Claystone_FloorRough.M_Claystone_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Claystone_FloorSmooth.M_Claystone_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Claystone_WallRough.M_Claystone_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Claystone_WallSmooth.M_Claystone_WallSmooth'",
        description = "A sedimentary rock formed largely from mud."
    },
    cobaltite = { name="Cobaltite", type="rock", layer="igneous", 
        glyph=glyphs['urk'], fg=colors['blue'], bg=colors['grey'],
        hit_points = 115, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Cobaltite_FloorRough.M_Cobaltite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Cobaltite_FloorSmooth.M_Cobaltite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_cobaltite_WallRough.M_cobaltite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Cobaltite_WallSmooth.M_Cobaltite_WallSmooth'",
        description = "Cobalt, arsenic and sulphur. Not tasty. Kobolds were named after this rock."
    },
    conglomerate = { name="Conglomerate", type="rock", layer="sedimentary", 
        glyph=glyphs['infinity'], fg=colors['yellow'], bg=colors['grey'],
        hit_points = 75, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Conglomerate_FloorRough.M_Conglomerate_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Conglomerate_FloorSmooth.M_Conglomerate_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Conglomerate_WallRough.M_Conglomerate_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Conglomerate_WallSmooth.M_Conglomerate_WallSmooth'",
        description = "A sedimentary rock formed largely from just about everything else."
    },
    copper_rock = { name="Native Copper", type="rock", layer="igneous", 
        glyph=glyphs['ukp'], fg=colors['copper'], bg=colors['grey'],
        hit_points = 75, mines_to="ore", ore_materials = {"copper"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_CopperRock_FloorRough.M_CopperRock_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_CopperRock_FloorSmooth.M_CopperRock_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_CopperRock_WallRough.M_CopperRock_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_CopperRock_WallSmooth.M_CopperRock_WallSmooth'",
        description = "Rock that contains streaks of copper."
    },
    dacite = { name="Dacite", type="rock", layer="igneous", 
        glyph=glyphs['period'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Dacite_FloorRough.M_Dacite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Dacite_FloorSmooth.M_Dacite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Dacite_WallRough.M_Dacite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Dacite_WallSmooth.M_Dacite_WallSmooth'",
        description = "A hard rock containing lots of quartz and feltspar."
    },
    diorite = { name="Diorite", type="rock", layer="igneous", 
        glyph=glyphs['one_quarter_solid'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Diorite_FloorRough.M_Diorite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Diorite_FloorSmooth.M_Diorite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Diorite_Wall_Rough.M_Diorite_Wall_Rough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Diorite_WallSmooth.M_Diorite_WallSmooth'",
        description = "A hard rock containing lots of quartz."
    },
    dolomite = { name="Dolomite", type="rock", layer="sedimentary", 
        glyph=glyphs['backtick'], fg=colors['white'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Dolomite_FloorRough.M_Dolomite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Dolomite_FloorSmooth.M_Dolomite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Dolomite_WallRough.M_Dolomite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Dolomite_WallSmooth.M_Dolomite_WallSmooth'",
        description = "A readily dissolved rock, frequently found in aquifers."
    },
    gabbro = { name="Gabbro", type="rock", layer="igneous", 
        glyph=glyphs['one_quarter_solid'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Gabbro_FloorRough.M_Gabbro_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Gabbro_FloorSmooth.M_Gabbro_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Gabbro_WallRough.M_Gabbro_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Gabbro_WallSmooth.M_Gabbro_WallSmooth'",
        description = "A dense rock, sometimes containing Olivine."
    },
    galena = { name="Galena", type="rock", layer="igneous", 
        glyph=glyphs['ukp'], fg=colors['white'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"lead", "silver"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Galena_FloorRough.M_Galena_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Galena_FloorSmooth.M_Galena_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Galena_WallRough.M_Galena_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Galena_WallSmooth.M_Galena_WallSmooth'",
        description = "A rock made up lead and sulphur. Sure to give you brain damage if consumed!"
    },
    garnierite = { name="Garnierite", type="rock", layer="cluster_rock", parent="gabbro",
        glyph=glyphs['ukp'], fg=colors['green'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"lead", "nickel"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Garnierite_FloorRough.M_Garnierite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Garnierite_FloorSmooth.M_Garnierite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Garnierite_WallRough.M_Garnierite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Garnierite_WallSmooth.M_Garnierite_WallSmooth'",
        description = "A nickel bearing green rock."
    },
    gneiss = { name="Gneiss", type="rock", layer="igneous", 
        glyph=glyphs['equals'], fg=colors['white'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Gneiss_FloorRough.M_Gneiss_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Gneiss_FloorSmooth.M_Gneiss_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Gneiss_WallRough.M_Gneiss_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Gneiss_WallSmooth.M_Gneiss_WallSmooth'",
        description = "A dense rock, also the subject of numerous puns amongst geologists."
    },
    gold_rock = { name="Native Gold", type="rock", layer="igneous", 
        glyph=glyphs['ukp'], fg=colors['yellow'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"gold"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_GoldRock_FloorRough.M_GoldRock_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_GoldRock_FloorSmooth.M_GoldRock_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_GoldRock_WallRough.M_GoldRock_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_GoldRock_WallSmooth.M_GoldRock_WallSmooth'",
        description = "A dense rock, streaked with veins of gold. Dwarves love it."
    },
    granite = { name="Granite", type="rock", layer="igneous", 
        glyph=glyphs['one_quarter_solid'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Granite_FloorRough.M_Granite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Granite_FloorSmooth.M_Granite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Granite_WallRough.M_Granite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Granite_WallSmooth.M_Granite_WallSmooth'",
        description = "A dense rock with lots of quartz."
    },
    graphite = { name="Graphite", type="rock", layer="cluster_rock", parent="gneiss",
        glyph=glyphs['circle'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Graphite_FloorRough.M_Graphite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Graphite_FloorSmooth.M_Graphite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Graphite_WallRough.M_Graphite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Graphite_WallSmooth.M_Graphite_WallSmooth'",
        description = "A cyrstalline black rock that generally ends up in pencils."
    },
    gypsum = { name="Gypsum", type="rock", layer="sedimentary", 
        glyph=glyphs['hash'], fg=colors['yellow'], bg=colors['grey'],
        hit_points = 100, mines_to="gypsum_powder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Gypsum_FloorRough.M_Gypsum_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Gypsum_FloorSmooth.M_Gypsum_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Gypsum_WallRough.M_Gypsum_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Gypsum_WallSmooth.M_Gypsum_WallSmooth'",
        description = "A white rock frequently ground into plaster."
    },
    hematite_ig = { name="Hematite", type="rock", layer="igneous", 
        glyph=glyphs['ukp'], fg=colors['red_sand'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"iron"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Hematite_FloorRough.M_Hematite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Hematite_FloorSmooth.M_Hematite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Hemaitite_WallRough.M_Hemaitite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Hematite_WallSmooth.M_Hematite_WallSmooth'",
        description = "An iron-bearing rock, reddish in hue from the rust."
    },
    hematite_se = { name="Hematite", type="rock", layer="sedimentary", 
        glyph=glyphs['ukp'], fg=colors['red_sand'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"iron"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Hematite_FloorRough.M_Hematite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Hematite_FloorSmooth.M_Hematite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Hemaitite_WallRough.M_Hemaitite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Hematite_WallSmooth.M_Hematite_WallSmooth'",
        description = "An iron-bearing rock, reddish in hue from the rust."
    },
    hornblende = { name="Hornblende", type="rock", layer="igneous", 
        glyph=glyphs['one_quarter_solid'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Hornblende_FloorRough.M_Hornblende_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Hornblende_FloorSmooth.M_Hornblende_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Hornblende_WallRough.M_Hornblende_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Hornblende_WallSmooth.M_Hornblende_WallSmooth'",
        description = "A mixture of minerals clumped together."
    },
    jet = { name="Jet", type="rock", layer="sedimentary", 
        glyph=glyphs['one_quarter_solid'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Jet_FloorRough.M_Jet_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Jet_FloorSmooth.M_Jet_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Jet_WallRough.M_Jet_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Jet_WallSmooth.M_Jet_WallSmooth'",
        description = "A hard, black rock."
    },
    kaolinite = { name="Kaolinite", type="rock", layer="sedimentary", 
        glyph=glyphs['equals'], fg=colors['red'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Kaolinite_FloorRough.M_Kaolinite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Kaolinute_FloorSmooth.M_Kaolinute_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Kaolinite_WallRough.M_Kaolinite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Kaolinite_WallSmooth.M_Kaolinite_WallSmooth'",
        description = "A white rock made up mostly of clay."
    },
    lignite = { name="Lignite", type="rock", layer="sedimentary", 
        glyph=glyphs['sun'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="coal",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Lignite_FloorRough.M_Lignite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Lignite_FloorSmooth.M_Lignite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Lignite_WallRough.M_Lignite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Lignite_WallSmoooth.M_Lignite_WallSmoooth'",
        description = "Sticky brown rock from which one can extract coal and tar."
    },
    limestone = { name="Limestone", type="rock", layer="sedimentary", 
        glyph=glyphs['one_quarter_solid'], fg=colors['white'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Limestone_FloorRough.M_Limestone_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Limestone_FloorSmooth.M_Limestone_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Limestone_WallRough.M_Limestone_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Limestone_Wall_Smooth.M_Limestone_Wall_Smooth'",
        description = "A soft, light-colored rock."
    },
    limonite = { name="Limonite", type="rock", layer="igneous", 
        glyph=glyphs['ukp'], fg=colors['yellow'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"iron"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Limonite_FloorRough.M_Limonite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Limonite_FloorSmooth.M_Limonite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Limonite_WallRough.M_Limonite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Limonite_WallSmooth.M_Limonite_WallSmooth'",
        description = "An iron bearing rock, containing lots of sulphur."
    },
    magnetite = { name="Magnetite", type="rock", layer="igneous", 
        glyph=glyphs['tilde'], fg=colors['red'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"iron"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Magnetite_FloorRough.M_Magnetite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Magnetite_FloorSmooth.M_Magnetite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Magnetite_WallRough.M_Magnetite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Magnetite_WallSmooth.M_Magnetite_WallSmooth'",
        description = "An iron-bearing rock, reddish in hue from the rust."
    },
    malachite = { name="Malachite", type="rock", layer="igneous", 
        glyph=glyphs['ukp'], fg=colors['green'], bg=colors['grey'],
        hit_points = 75, mines_to="ore", ore_materials = {"copper"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Malachite_FloorRough.M_Malachite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Malachite_FloorSmooth.M_Malachite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Malachite_Wall_Smooth.M_Malachite_Wall_Smooth'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Malachite_WallRough.M_Malachite_WallRough'",
        description = "A green rock, frequently found in stalagtites."
    },
    marble = { name="Marble", type="rock", layer="sedimentary", 
        glyph=glyphs['one_quarter_solid'], fg=colors['white'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Marble_FloorRough.M_Marble_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Marble_FloorSmooth.M_Marble_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Marble_WallRough.M_Marble_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Marble_Wall_Smooth.M_Marble_Wall_Smooth'",
        description = "A soft, light-colored rock popular in architecture."
    },
    microcline = { name="Microcline", type="rock", layer="igneous", 
        glyph=glyphs['percent'], fg=colors['cyan'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Microcline_FloorRough.M_Microcline_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Microcline_FloorSmooth.M_Microcline_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Microcline_WallRough.M_Microcline_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Microcline_WallSmooth.M_Microcline_WallSmooth'",
        description = "A hard rock with a pleasant blue color."
    },
    mudstone = { name="Marble", type="rock", layer="sedimentary", 
        glyph=glyphs['double_wave'], fg=colors['yellow'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Mudstone_FloorRough.M_Mudstone_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Mudstone_FloorSmooth.M_Mudstone_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Mudstone_WallRough.M_Mudstone_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Mudstone_WallSmooth.M_Mudstone_WallSmooth'",
        description = "A sedimentary rock formed largely from just about everything else."
    },
    obsidian = { name="Obsidian", type="rock", layer="igneous", 
        glyph=glyphs['one_quarter_solid'], fg=colors['white'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder", damage_bonus=1,
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Obsidian_FloorRough.M_Obsidian_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Obsidian_FloorSmooth.M_Obsidian_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Obsidian_WallRough.M_Obsidian_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Obsidian_WallSmooth.M_Obsidian_WallSmooth'",
        description = "Volcanic glass rock."
    },
    olivine = { name="Olivine", type="rock", layer="igneous", 
        glyph=glyphs['percent'], fg=colors['green'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Olivine_FloorRough.M_Olivine_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Olivine_FloorSmooth.M_Olivine_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Olivine_WallRough.M_Olivine_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Olivine_WallSmooth.M_Olivine_WallSmooth'",
        description = "A green crystalline rock."
    },
    orpiment = { name="Orpiment", type="rock", layer="igneous",
        glyph=glyphs['yellow'], fg=colors['tilde'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Orpiment_FloorRough.M_Orpiment_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Orpiment_FloorSmooth.M_Orpiment_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Orpiment_WallRough.M_Orpiment_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Orpiment_WallSmooth.M_Orpiment_WallSmooth'",
        description = "An igneous rock, yellow from sulphur."
    },
    orthoclase = { name="Orthoclase", type="rock", layer="igneous", 
        glyph=glyphs['percent'], fg=colors['yellow'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Orthoclase_FloorRough.M_Orthoclase_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Orthoclase_FloorSmooth.M_Orthoclase_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Orthoclase_WallRough.M_Orthoclase_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Orthoclase_WallSmooth.M_Orthoclase_WallSmooth'",
        description = "A dense rock with lots of quartz."
    },
    phylite = { name="Phylite", type="rock", layer="sedimentary", 
        glyph=glyphs['minus'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Phylite_FloorRough.M_Phylite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Phylite_FloorSmooth.M_Phylite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Phylite_Wall_Rough.M_Phylite_Wall_Rough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Phylite_WallSmooth.M_Phylite_WallSmooth'",
        description = "A dense rock with lots of quartz."
    },
    pitchblende = { name="Pitchblende", type="rock", layer="igneous", 
        glyph=glyphs['star'], fg=colors['purple'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"uranium"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Pitchblende_FloorRough.M_Pitchblende_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Pitchblende_FloorSmooth.M_Pitchblende_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Pitchblende_WallRough.M_Pitchblende_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Pitchblende_WallSmooth.M_Pitchblende_WallSmooth'",
        description = "A green rock containing Uranium. People used to grind this up for paint."
    },
    platinum_rock = { name="Native Platinum", type="rock", layer="igneous", 
        glyph=glyphs['ukp'], fg=colors['white'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"platinum"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_PlatinumRock_FloorRough.M_PlatinumRock_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_PlatinumRock_FloorSmooth.M_PlatinumRock_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_PlatinumRock_WallRough.M_PlatinumRock_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_PlatinumRock_WallSmooth.M_PlatinumRock_WallSmooth'",
        description = "A dense rock, streaked with veins of platinum. Dwarves love it."
    },
    pyrolusite = { name="Pyrolusite", type="rock", layer="igneous", 
        glyph=glyphs['percent'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Pyrolusite_FloorRough.M_Pyrolusite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Pyrolusite_FloorSmooth.M_Pyrolusite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Pyrolusite_WallRough.M_Pyrolusite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Pyrolusite_WallSmooth.M_Pyrolusite_WallSmooth'",
        description = "A dense rock with lots of quartz."
    },
    quartzite = { name="Quartzite", type="rock", layer="igneous", 
        glyph=glyphs['minus'], fg=colors['white'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Quartzite_FloorRough.M_Quartzite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Quartzite_FloorSmooth.M_Quartzite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Quartzite_WallRough.M_Quartzite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Quartzite_WallSmooth.M_Quartzite_WallSmooth'",
        description = "A dense rock with lots of quartz."
    },
    realgar = { name="Realgar", type="rock", layer="igneous", 
        glyph=glyphs['percent'], fg=colors['red'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Realgar_FloorRough.M_Realgar_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Realgar_FloorSmooth.M_Realgar_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Realgar_WallRough.M_Realgar_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Realgar_WallSmooth.M_Realgar_WallSmooth'",
        description = "A dense rock with lots of quartz."
    },
    rhyolite = { name="Rhyolite", type="rock", layer="igneous", 
        glyph=glyphs['comma'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Rhyolite_FloorRough.M_Rhyolite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Rhyolite_FloorSmooth.M_Rhyolite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Rhyolite_Wall_Smooth.M_Rhyolite_Wall_Smooth'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Rhyolite_WallRough.M_Rhyolite_WallRough'",
        description = "A dense rock with lots of quartz."
    },
    rock_salt = { name="Rock Salt", type="rock", layer="sedimentary", 
        glyph=glyphs['hash'], fg=colors['white'], bg=colors['grey'],
        hit_points = 50, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Rocksalt_FloorRough.M_Rocksalt_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Rocksalt_FloorSmooth.M_Rocksalt_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Rocksalt_WallRough.M_Rocksalt_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Rocksalt_Wall_Smooth.M_Rocksalt_Wall_Smooth'",
        description = "Salt crystals, crammed together into a rock."
    },
    rutile = { name="Rutile", type="rock", layer="igneous", 
        glyph=glyphs['backtick'], fg=colors['purple'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"uranium"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Rutile_FloorRough.M_Rutile_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Rutile_FloorSmooth.M_Rutile_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Rutile_WallRough.M_Rutile_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Rutile_WallSmooth.M_Rutile_WallSmooth'",
        description = "A hard, black rock made from titantium oxide."
    },
    saltpeter = { name="Saltpeter", type="rock", layer="sedimentary", 
        glyph=glyphs['hash'], fg=colors['yellow'], bg=colors['grey'],
        hit_points = 50, mines_to="saltpeter_ore",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Saltpeter_FloorRough.M_Saltpeter_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Saltpeter_FloorSmooth.M_Saltpeter_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Saltpeter_WallRough.M_Saltpeter_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Saltpeter_Wall_Smooth.M_Saltpeter_Wall_Smooth'",
        description = "A primary component of gunpowder."
    },
    sandstone = { name="Sandstone", type="rock", layer="sedimentary", 
        glyph=glyphs['hash'], fg=colors['yellow'], bg=colors['grey'],
        hit_points = 50, mines_to="sand",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Sandstone_FloorRough.M_Sandstone_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Sandstone_FloorSmooth.M_Sandstone_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Sandstone_WallRough.M_Sandstone_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Sandstone_WallSmooth.M_Sandstone_WallSmooth'",
        description = "A sandy stone."
    },
    serpentine = { name="Serpentine", type="rock", layer="igneous", 
        glyph=glyphs['double_wave'], fg=colors['green'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Serpentine_FloorRough.M_Serpentine_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Serpentine_FloorSmooth.M_Serpentine_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Serpentine_WallRough.M_Serpentine_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Serpentine_Wall_Smooth.M_Serpentine_Wall_Smooth'",
        description = "A green crystalline rock."
    },
    shale = { name="Shale", type="rock", layer="sedimentary", 
        glyph=glyphs['period'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 50, mines_to="oil",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Shale_FloorRough.M_Shale_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Shale_FloorSmooth.M_Shale_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Shale_WallRough.M_Shale_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Shale_WallSmooth.M_Shale_WallSmooth'",
        description = "A soft, light-colored rock often containing oil."
    },
    siltstone = { name="Siltstone", type="rock", layer="sedimentary",
        glyph=glyphs['percent'], fg=colors['yellow'], bg=colors['grey'],
        hit_points = 50, mines_to="oil",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Siltstone_FloorRough.M_Siltstone_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Siltstone_FloorSmooth.M_Siltstone_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Siltstone_WallRough.M_Siltstone_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Siltstone_WallSmooth.M_Siltstone_WallSmooth'",
        description = "A soft, light-colored rock."
    },
    silver_rock = { name="Native Silver", type="rock", layer="igneous", 
        glyph=glyphs['ukp'], fg=colors['white'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"silver"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_SilverRock_FloorRough.M_SilverRock_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_SilverRock_FloorSmooth.M_SilverRock_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_SilverRock_WallRough.M_SilverRock_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_SilverRock_WallSmooth.M_SilverRock_WallSmooth'",
        description = "A dense rock, streaked with veins of silver. Dwarves kinda like it."
    },
    sphalerite_rock = { name="Sphalerite", type="rock", layer="sedimentary", 
        glyph=glyphs['ukp'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"zinc"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Sphalerite_FloorRough.M_Sphalerite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Sphalerite_FloorSmooth.M_Sphalerite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Sphalerite_WallRough.M_Sphalerite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Sphalerite_WallSmooth.M_Sphalerite_WallSmooth'",
        description = "A zinc-bearing rock."
    },
    stibnite = { name="Stibnite", type="rock", layer="igneous", 
        glyph=glyphs['percent'], fg=colors['white'], bg=colors['grey'],
        hit_points = 100, mines_to="stone_boulder",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Stibnite_FloorRough.M_Stibnite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Stibnite_FloorSmooth.M_Stibnite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Stibnite_Wall_Smooth.M_Stibnite_Wall_Smooth'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Stibnite_WallRough.M_Stibnite_WallRough'",
        description = "A crystalline rock."
    },
    tetrahedrite = { name="Tetrahedrite", type="rock", layer="igneous", 
        glyph=glyphs['ukp'], fg=colors['copper'], bg=colors['grey'],
        hit_points = 100, mines_to="ore", ore_materials = {"copper", "silver"},
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Tetrahedrite_FloorRough.M_Tetrahedrite_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Tetrahedrite_FloorSmooth.M_Tetrahedrite_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Tetrahedrite_WallRough.M_Tetrahedrite_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/M_Tetrahedrite_WallSmooth.M_Tetrahedrite_WallSmooth'",
        description = "A dense rock, streaked with veins of silver and copper. Rated 9/10 by most Dwarves."
    },

    -- Soils

    clay_soil = { name="Clay", type="soil",
        glyph = glyphs['solid_square'], fg=colors['red'], bg=colors['black'],
        hit_points = 20, mines_to="clay",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_FloorRough.MA_ClaySoil_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_FloorSmooth.MA_ClaySoil_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_WallRough.MA_ClaySoil_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_WallSmooth.MA_ClaySoil_WallSmooth'",
        description = ""
    },
    clay_loam = { name="Clay Loam", type="soil",
        glyph = glyphs['one_quarter_solid'], fg=colors['red'], bg=colors['grey'],
        hit_points = 20, mines_to="clay",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClayLoam_FloorRough.MA_ClayLoam_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClayLoam_FloorSmooth.MA_ClayLoam_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClayLoam_WallRough.MA_ClayLoam_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClayLoam_WallSmooth.MA_ClayLoam_WallSmooth'",
        description = ""
    },
    loam = { name="Loam", type="soil",
        glyph = glyphs['one_quarter_solid'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 15, mines_to="topsoil",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Loam_FloorRough.MA_Loam_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Loam_FloorSmooth.MA_Loam_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Loam_WallRough.MA_Loam_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Loam_WallSmooth.MA_Loam_WallSmooth'",
        description = ""
    },
    loamy_sand = { name="Loamy Sand", type="soil",
        glyph = glyphs['one_quarter_solid'], fg=colors['yellow'], bg=colors['grey'],
        hit_points = 15, mines_to="topsoil",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_LoamySand_FloorRough.MA_LoamySand_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_LoamySand_FloorSmooth.MA_LoamySand_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_LoamySand_WallRough.MA_LoamySand_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_LoamySand_WallSmooth.MA_LoamySand_WallSmooth'",
        description = ""
    },
    peat = { name="Peat", type="soil",
        glyph = glyphs['one_quarter_solid'], fg=colors['yellow'], bg=colors['grey'],
        hit_points = 15, mines_to="topsoil",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Peat_FloorRough.MA_Peat_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Peat_FloorSmooth.MA_Peat_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Peat_WallRough.MA_Peat_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Peat_WallSmooth.MA_Peat_WallSmooth'",
        description = ""
    },
    sandy_clay = { name="Sandy Clay", type="soil",
        glyph = glyphs['one_quarter_solid'], fg=colors['wood_brown'], bg=colors['red'],
        hit_points = 15, mines_to="clay",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_FloorRough.MA_ClaySoil_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_FloorSmooth.MA_ClaySoil_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_WallRough.MA_ClaySoil_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_WallSmooth.MA_ClaySoil_WallSmooth'",
        description = ""
    },
    sandy_clay_loam = { name="Sandy Clay Loam", type="soil",
        glyph = glyphs['one_quarter_solid'], fg=colors['red'], bg=colors['yellow'],
        hit_points = 15, mines_to="topsoil", mines_to_also="clay",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_FloorRough.MA_ClaySoil_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_FloorSmooth.MA_ClaySoil_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_WallRough.MA_ClaySoil_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_WallSmooth.MA_ClaySoil_WallSmooth'",
        description = ""
    },
    silt = { name="Silt", type="soil",
        glyph = glyphs['one_quarter_solid'], fg=colors['yellow'], bg=colors['black'],
        hit_points = 15, mines_to="topsoil",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_FloorRough.MA_ClaySoil_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_FloorSmooth.MA_ClaySoil_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_WallRough.MA_ClaySoil_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_WallSmooth.MA_ClaySoil_WallSmooth'",
        description = ""
    },
    silty_clay = { name="Silty Clay", type="soil",
        glyph = glyphs['one_quarter_solid'], fg=colors['red'], bg=colors['black'],
        hit_points = 15, mines_to="clay",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_FloorRough.MA_ClaySoil_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_FloorSmooth.MA_ClaySoil_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_WallRough.MA_ClaySoil_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_WallSmooth.MA_ClaySoil_WallSmooth'",
        description = ""
    },
    silty_clay_loam = { name="Silty Clay Loam", type="soil",
        glyph = glyphs['one_quarter_solid'], fg=colors['red'], bg=colors['grey'],
        hit_points = 15, mines_to="topsoil",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_FloorRough.MA_ClaySoil_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_FloorSmooth.MA_ClaySoil_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_WallRough.MA_ClaySoil_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_WallSmooth.MA_ClaySoil_WallSmooth'",
        description = ""
    },
    silt_loam = { name="Silt Loam", type="soil",
        glyph = glyphs['one_quarter_solid'], fg=colors['grey'], bg=colors['grey'],
        hit_points = 15, mines_to="topsoil",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_FloorRough.MA_ClaySoil_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_FloorSmooth.MA_ClaySoil_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_WallRough.MA_ClaySoil_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_ClaySoil_WallSmooth.MA_ClaySoil_WallSmooth'",
        description = ""
    },
    sand = { name="Sand", type="sand",
        glyph = glyphs['one_quarter_solid'], fg=colors['yellow'], bg=colors['red'],
        hit_points = 10, mines_to="sand",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Sand_FloorRough.MA_Sand_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Sand_FloorSmooth.MA_Sand_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Sand_WallRough.MA_Sand_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Sand_WallSmooth.MA_Sand_WallSmooth'",
        description = ""
    },
    black_sand = { name="Black Sand", type="sand",
        glyph = glyphs['one_quarter_solid'], fg=colors['grey'], bg=colors['black'],
        hit_points = 10, mines_to="sand",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_BlackSand_FloorRough.MA_BlackSand_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_BlackSand_FloorSmooth.MA_BlackSand_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_BlackSand_WallRough.MA_BlackSand_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_BlackSand_WallSmooth.MA_BlackSand_WallSmooth'",
        description = ""
    },
    red_sand = { name="Red Sand", type="sand",
        glyph = glyphs['one_quarter_solid'], fg=colors['red_sand'], bg=colors['black'],
        hit_points = 10, mines_to="sand",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_RedSand_FloorRough.MA_RedSand_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_RedSand_FloorSmooth.MA_RedSand_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_RedSand_WallRough.MA_RedSand_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_RedSand_WallSmooth.MA_RedSand_WallSmooth'",
        description = ""
    },
    white_sand = { name="Sand", type="sand",
        glyph = glyphs['one_quarter_solid'], fg=colors['white_sand'], bg=colors['black'],
        hit_points = 10, mines_to="sand",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Sand_FloorRough.MA_Sand_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Sand_FloorSmooth.MA_Sand_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Sand_WallRough.MA_Sand_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Sand_WallSmooth.MA_Sand_WallSmooth'",
        description = ""
    },
    yellow_sand = { name="Yellow Sand", type="sand",
        glyph = glyphs['one_quarter_solid'], fg=colors['yellow_sand'], bg=colors['black'],
        hit_points = 10, mines_to="sand",
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Sand_FloorRough.MA_Sand_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Sand_FloorSmooth.MA_Sand_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Sand_WallRough.MA_Sand_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MA_Sand_WallSmooth.MA_Sand_WallSmooth'",
        description = ""
    },

-- Other materials needed
    wood = { name = "Wood", type="synthetic", 
        glyph = glyphs['one_quarter_solid'], fg=colors['wood_brown'], bg=colors['black'],
        hit_points = 20,
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_Wood_FloorRough.MB_Wood_FloorRough'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_Wood_FloorSmooth.MB_Wood_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_Wood_WallRough.MB_Wood_WallRough'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_Wood_WallSmooth.MB_Wood_WallSmooth'"
    },
    brick = { name = "Brick", type="synthetic", 
        glyph = glyphs['one_quarter_solid'], fg=colors['wood_brown'], bg=colors['black'],
        hit_points = 100,
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_Brick_FloorSmooth.MB_Brick_FloorSmooth'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_Brick_FloorSmooth.MB_Brick_FloorSmooth'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_Brick_WallSmooth.MB_Brick_WallSmooth'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_Brick_WallSmooth.MB_Brick_WallSmooth'"
    },
    organic = { name = "Organic", type="organic", 
        glyph = glyphs['one_quarter_solid'], fg=colors['red'], bg=colors['black'],
        hit_points = 10
    },
    blight = { name = "Blight", type="blight",
        glyph = glyphs['blight'], fg=colors['brown'], bg=colors['black'],
        hit_points = 10,
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_Blight.MB_Blight'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_Blight.MB_Blight'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_Blight.MB_Blight'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_Blight.MB_Blight'"
    },
    food = { name = "Food:", type="food", 
        glyph = glyphs['one_quarter_solid'], fg=colors['red'], bg=colors['black'],
        hit_points = 10
    },
    spice = { name = "Spice:", type="spice", 
        glyph = glyphs['one_quarter_solid'], fg=colors['red'], bg=colors['black'],
        hit_points = 10
    },
    bone = { name = "Organic", type="organic", 
        glyph = glyphs['one_quarter_solid'], fg=colors['white'], bg=colors['black'],
        hit_points = 10, damage_bonus=1
    },
    hide = { name = "Hide", type="leather", 
        glyph = glyphs['one_quarter_solid'], fg=colors['red'], bg=colors['black'],
        hit_points = 10, ac_bonus = 0.5
    },
    leather = { name = "Leather", type="leather", 
        glyph = glyphs['one_quarter_solid'], fg=colors['red'], bg=colors['black'],
        hit_points = 10, ac_bonus = 0.75
    },
    boiled_leather = { name = "Boiled Leather", type="leather", 
        glyph = glyphs['one_quarter_solid'], fg=colors['red'], bg=colors['black'],
        hit_points = 10, ac_bonus = 1.0
    },

-- Synthetic Materials - only occur after refining
    plasteel = { name = "Plasteel", type="synthetic", 
        glyph = glyphs['one_quarter_solid'], fg=colors['white'], bg=colors['black'],
        hit_points = 200,
        FloorRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_BathTile.MB_BathTile'",
        FloorSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_BathTile.MB_BathTile'",
        WallRough = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_Plasteel_Wall.MB_Plasteel_Wall'",
        WallSmooth = "MaterialInstanceConstant'/Game/TileMaterials/Instances/MB_Plasteel_Wall.MB_Plasteel_Wall'"
    },
    cloth = { name = "Cloth", type="organic", 
        glyph = glyphs['one_quarter_solid'], fg=colors['red'], bg=colors['black'],
        hit_points = 10, ac_bonus = 0.0
    },

-- Metals
    aluminium = { name = "Aluminium", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['aluminium_blue'], bg=colors['black'],
        hit_points = 200, damage_bonus=-1, ac_bonus=0.5
    },
    bismuth = { name = "Bismuth", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['bronze'], bg=colors['black'],
        hit_points = 200, damage_bonus=1, ac_bonus=0.5
    },
    bronze = { name = "Bronze", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['bronze'], bg=colors['black'],
        hit_points = 200, damage_bonus=2, ac_bonus=1.0
    },
    copper = { name = "Copper", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['copper'], bg=colors['black'],
        hit_points = 200, damage_bonus=1, ac_bonus=0.5
    },
    chromium = { name = "Chromium", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['chromium_blue'], bg=colors['black'],
        hit_points = 200, damage_bonus=3, ac_bonus=1.0
    },
    gold = { name = "Gold", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['gold'], bg=colors['black'],
        hit_points = 200, damage_bonus=1, ac_bonus=0.5
    },
    iron = { name = "Iron", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['grey'], bg=colors['black'],
        hit_points = 200, damage_bonus=3, ac_bonus=2.0
    },
    steel = { name = "Steel", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['grey'], bg=colors['black'],
        hit_points = 200, damage_bonus=4, ac_bonus=3.0
    },
    lead = { name = "Lead", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['grey'], bg=colors['black'],
        hit_points = 200, damage_bonus=-1, ac_bonus=0.5
    },
    nickel = { name = "Nickel", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['grey'], bg=colors['black'],
        hit_points = 200, damage_bonus=-1, ac_bonus=0.5
    },
    platinum = { name = "Lead", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['silver'], bg=colors['black'],
        hit_points = 200, damage_bonus=1, ac_bonus=1.0
    },
    silver = { name = "Silver", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['silver'], bg=colors['black'],
        hit_points = 200, damage_bonus=1, ac_bonus=1.0
    },
    tin = { name = "Tin", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['tin_blue'], bg=colors['black'],
        hit_points = 200, damage_bonus=-1, ac_bonus=0.5
    },
    uranium = { name = "Uranium", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['green'], bg=colors['black'],
        hit_points = 200, damage_bonus=4, ac_bonus=4.0
    },
    zinc = { name = "Zinc", type="metal", 
        glyph = glyphs['one_quarter_solid'], fg=colors['tin_blue'], bg=colors['black'],
        hit_points = 200, damage_bonus=-1, ac_bonus=0.5
    },
}
